In [2]:
import numpy as np
import pandas as pd

In [3]:
airbnb = pd.read_csv('airbnb.csv', index_col='Unnamed: 0')

In [4]:
airbnb.describe()

,listing_id,host_id,number_of_reviews,reviews_per_month,availability_365,rating,number_of_stays,5_stars
count,1.001900e+04,1.001900e+04,10019.000000,7944.000000,10019.000000,7944.000000,7944.000000,7944.000000
mean,1.927634e+07,6.795923e+07,22.459727,1.353894,112.284260,4.014458,33.991541,0.718599
std,1.095056e+07,7.863106e+07,43.173896,1.615380,131.636043,0.575064,56.089279,0.079978
min,3.831000e+03,2.787000e+03,0.000000,0.010000,0.000000,3.000633,1.200000,0.600026
25%,9.674772e+06,7.910880e+06,1.000000,0.200000,0.000000,3.520443,3.600000,0.655576
50%,2.007030e+07,3.165167e+07,5.000000,0.710000,44.000000,4.027965,10.800000,0.709768
75%,2.933864e+07,1.074344e+08,22.000000,2.000000,226.000000,4.516378,38.400000,0.763978
max,3.648724e+07,2.741034e+08,510.000000,16.220000,365.000000,5.181114,612.000000,0.950339

In [5]:
airbnb['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Private', 'Shared room',
       'PRIVATE ROOM', 'home', '   Shared room      '], dtype=object)

In [6]:
airbnb['room_type'].value_counts()

room_type
Entire home/apt         5120
Private room            4487
Shared room              155
Private                   89
   Shared room            71
home                      66
PRIVATE ROOM              31
Name: count, dtype: int64

In [7]:
airbnb['coordinates']=airbnb['coordinates'].str.replace("(","")
airbnb['coordinates']=airbnb['coordinates'].str.replace(")","")
airbnb['coordinates'].head()

0    40.63222, -73.93398
1    40.78761, -73.96862
2     40.7007, -73.99517
3    40.79169, -73.97498
4    40.71884, -73.98354
Name: coordinates, dtype: object

In [8]:
lat_long = airbnb['coordinates'].str.split(",",expand=True)
lat_long.head()

          0           1
0  40.63222   -73.93398
1  40.78761   -73.96862
2   40.7007   -73.99517
3  40.79169   -73.97498
4  40.71884   -73.98354

In [9]:
airbnb['latitude']=lat_long[0]

In [10]:
airbnb['longitude']=lat_long[1]
airbnb.head()

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","40.63222, -73.93398",Private room,45$,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","40.78761, -73.96862",Entire home/apt,135$,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","40.7007, -73.99517",Entire home/apt,150$,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15,40.7007,-73.99517
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","40.79169, -73.97498",Entire home/apt,86$,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","40.71884, -73.98354",Private room,160$,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354

In [11]:
airbnb.dtypes

listing_id              int64
name                   object
host_id                 int64
host_name              object
neighbourhood_full     object
coordinates            object
room_type              object
price                  object
number_of_reviews       int64
last_review            object
reviews_per_month     float64
availability_365        int64
rating                float64
number_of_stays       float64
5_stars               float64
listing_added          object
latitude               object
longitude              object
dtype: object

In [12]:
airbnb['latitude']=airbnb['latitude'].astype('float')

In [13]:
airbnb['longitude']=airbnb['longitude'].astype('float')

In [14]:
airbnb['price']=airbnb['price'].str.strip("$")

In [15]:
airbnb['price'].head()

0     45
1    135
2    150
3     86
4    160
Name: price, dtype: object

In [16]:
airbnb['price']=airbnb['price'].astype('float')
airbnb['price'].mean()

np.float64(150.90512217564665)

In [17]:
airbnb[['listing_added','last_review']].head()

  listing_added last_review
0    2018-06-08  2018-12-12
1    2018-12-25  2019-06-30
2    2018-08-15         NaN
3    2017-03-20  2017-09-23
4    2020-10-23  2019-06-12

In [18]:
airbnb['listing_added']=pd.to_datetime(airbnb['listing_added'],format='%Y-%m-%d')
airbnb['last_review']=pd.to_datetime(airbnb['last_review'],format='%Y-%m-%d')

In [19]:
airbnb[['listing_added','last_review']].head()

  listing_added last_review
0    2018-06-08  2018-12-12
1    2018-12-25  2019-06-30
2    2018-08-15         NaT
3    2017-03-20  2017-09-23
4    2020-10-23  2019-06-12

In [20]:
airbnb['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Private', 'Shared room',
       'PRIVATE ROOM', 'home', '   Shared room      '], dtype=object)

In [21]:
airbnb['room_type']=airbnb['room_type'].str.lower()

In [22]:
airbnb['room_type'].unique()

array(['private room', 'entire home/apt', 'private', 'shared room',
       'home', '   shared room      '], dtype=object)

In [23]:
airbnb['room_type'] = airbnb['room_type'].str.strip()
airbnb['room_type'].unique()

array(['private room', 'entire home/apt', 'private', 'shared room',
       'home'], dtype=object)

In [24]:
mappings={
    'private room':'Private Room',
    'private':'Private Room',
    'entire home/apt':'Entire place',
    'shared room': 'Shared room',
    'home': 'Entire place'
}
airbnb['room_type']=airbnb['room_type'].replace(mappings)
airbnb['room_type'].unique()

array(['Private Room', 'Entire place', 'Shared room'], dtype=object)

In [25]:
airbnb['neighbourhood_full'].head()

0           Brooklyn, Flatlands
1    Manhattan, Upper West Side
2    Brooklyn, Brooklyn Heights
3    Manhattan, Upper West Side
4    Manhattan, Lower East Side
Name: neighbourhood_full, dtype: object

In [26]:
borough_neighbourhood = airbnb['neighbourhood_full'].str.split(",",expand=True)
borough_neighbourhood.head()

           0                  1
0   Brooklyn          Flatlands
1  Manhattan    Upper West Side
2   Brooklyn   Brooklyn Heights
3  Manhattan    Upper West Side
4  Manhattan    Lower East Side

In [27]:
airbnb['borough']=borough_neighbourhood[0]
airbnb['neighbourhood']=borough_neighbourhood[1]

In [28]:
airbnb[['neighbourhood_full','borough','neighbourhood']].head()

           neighbourhood_full    borough      neighbourhood
0         Brooklyn, Flatlands   Brooklyn          Flatlands
1  Manhattan, Upper West Side  Manhattan    Upper West Side
2  Brooklyn, Brooklyn Heights   Brooklyn   Brooklyn Heights
3  Manhattan, Upper West Side  Manhattan    Upper West Side
4  Manhattan, Lower East Side  Manhattan    Lower East Side

In [29]:
airbnb.drop('neighbourhood_full',axis=1,inplace=True)

In [30]:
airbnb['borough'].unique()

array(['Brooklyn', 'Manhattan', 'Queens', 'Bronx', 'Staten Island'],
      dtype=object)

In [31]:
airbnb['neighbourhood'].unique()

array([' Flatlands', ' Upper West Side', ' Brooklyn Heights',
       ' Lower East Side', ' Greenwich Village', ' Harlem',
       ' Sheepshead Bay', ' Theater District', ' Bushwick', ' Laurelton',
       ' Mott Haven', ' Flushing', ' Crown Heights', ' Midtown',
       ' Financial District', ' East Village', ' Park Slope',
       ' Washington Heights', ' Williamsburg', ' Chelsea',
       ' Bedford-Stuyvesant', ' Gowanus', ' Upper East Side',
       ' Ditmars Steinway', ' Cypress Hills', " Hell's Kitchen",
       ' Ridgewood', ' Marble Hill', ' Kips Bay', ' Prospect Heights',
       ' East New York', ' Concord', ' Stapleton', ' Astoria',
       ' East Harlem', ' Sunnyside', ' Gramercy',
       ' Prospect-Lefferts Gardens', ' Sunset Park', ' Forest Hills',
       ' Windsor Terrace', ' Clinton Hill', ' Murray Hill',
       ' Flatiron District', ' Greenpoint', ' East Flatbush', ' Tribeca',
       ' Woodhaven', ' Fort Greene', ' Inwood', ' Chinatown',
       ' Rockaway Beach', ' Woodside', ' Bayside', ' Bensonhurst',
       ' SoHo', ' Red Hook', ' West Village', ' South Slope',
       ' Richmond Hill', ' Jamaica', ' Boerum Hill', ' St. George',
       ' Clason Point', ' College Point', ' Vinegar Hill', ' Rego Park',
       ' East Elmhurst', ' Kensington', ' Roosevelt Island',
       ' Ozone Park', ' Arverne', ' Fordham', ' Wakefield',
       ' Port Morris', ' Flatbush', ' Elmhurst', ' Bay Ridge',
       ' Canarsie', ' Little Italy', ' Civic Center', ' St. Albans',
       ' Morningside Heights', ' Morrisania', ' Two Bridges',
       ' Concourse', ' Downtown Brooklyn', ' Queens Village',
       ' Fieldston', ' Allerton', ' Grymes Hill', ' Carroll Gardens',
       ' Kingsbridge', ' Belle Harbor', ' NoHo', ' Maspeth',
       ' Borough Park', ' Midwood', ' Fresh Meadows',
       ' Battery Park City', ' Pelham Bay', ' Van Nest',
       ' Long Island City', ' Williamsbridge', ' Nolita', ' Kew Gardens',
       ' Corona', ' Middle Village', ' Jackson Heights', ' Gravesend',
       ' New Dorp Beach', ' Brighton Beach', ' Belmont', ' Eltingville',
       ' South Ozone Park', ' Stuyvesant Town', ' Far Rockaway',
       ' Longwood', ' Glendale', ' Dongan Hills', ' Hollis',
       ' Columbia St', ' Tompkinsville', ' Springfield Gardens',
       ' Concourse Village', ' Throgs Neck', ' Cobble Hill',
       ' South Beach', ' North Riverdale', ' Rosedale', ' Mount Hope',
       ' Edenwald', ' Parkchester', ' Mill Basin', ' Brownsville',
       ' Fort Hamilton', ' Howard Beach', ' Claremont Village',
       ' Pelham Gardens', ' Westchester Square', ' Kew Gardens Hills',
       ' Arrochar', ' Edgemere', ' Shore Acres', ' Dyker Heights',
       ' Mount Eden', ' Randall Manor', ' Jamaica Hills', ' Norwood',
       ' Tottenville', ' Cambria Heights', ' East Morrisania',
       ' Soundview', ' Morris Park', ' Bronxdale', ' Bellerose',
       ' Navy Yard', ' Unionport', ' DUMBO', ' Bayswater', ' Tremont',
       ' Highbridge', ' Graniteville', ' Baychester', ' Morris Heights',
       ' Coney Island', ' Briarwood', ' West Farms', " Prince's Bay",
       ' University Heights', ' Clifton', ' Bay Terrace', ' City Island',
       ' West Brighton', ' Douglaston', ' Schuylerville',
       ' Port Richmond', ' Oakwood', ' Westerleigh', ' Little Neck',
       ' Holliswood', ' Bergen Beach', ' Castle Hill', ' Olinville',
       ' Rosebank', ' Melrose', ' Whitestone', ' Grant City',
       ' Riverdale', ' Neponsit', ' Bath Beach', ' Mariners Harbor',
       ' Hunts Point', ' Great Kills', ' Midland Beach', ' Eastchester',
       ' Jamaica Estates', ' New Springville'], dtype=object)

In [32]:
airbnb['neighbourhood']=airbnb['neighbourhood'].str.strip()
airbnb['neighbourhood'].unique()

array(['Flatlands', 'Upper West Side', 'Brooklyn Heights',
       'Lower East Side', 'Greenwich Village', 'Harlem', 'Sheepshead Bay',
       'Theater District', 'Bushwick', 'Laurelton', 'Mott Haven',
       'Flushing', 'Crown Heights', 'Midtown', 'Financial District',
       'East Village', 'Park Slope', 'Washington Heights', 'Williamsburg',
       'Chelsea', 'Bedford-Stuyvesant', 'Gowanus', 'Upper East Side',
       'Ditmars Steinway', 'Cypress Hills', "Hell's Kitchen", 'Ridgewood',
       'Marble Hill', 'Kips Bay', 'Prospect Heights', 'East New York',
       'Concord', 'Stapleton', 'Astoria', 'East Harlem', 'Sunnyside',
       'Gramercy', 'Prospect-Lefferts Gardens', 'Sunset Park',
       'Forest Hills', 'Windsor Terrace', 'Clinton Hill', 'Murray Hill',
       'Flatiron District', 'Greenpoint', 'East Flatbush', 'Tribeca',
       'Woodhaven', 'Fort Greene', 'Inwood', 'Chinatown',
       'Rockaway Beach', 'Woodside', 'Bayside', 'Bensonhurst', 'SoHo',
       'Red Hook', 'West Village', 'South Slope', 'Richmond Hill',
       'Jamaica', 'Boerum Hill', 'St. George', 'Clason Point',
       'College Point', 'Vinegar Hill', 'Rego Park', 'East Elmhurst',
       'Kensington', 'Roosevelt Island', 'Ozone Park', 'Arverne',
       'Fordham', 'Wakefield', 'Port Morris', 'Flatbush', 'Elmhurst',
       'Bay Ridge', 'Canarsie', 'Little Italy', 'Civic Center',
       'St. Albans', 'Morningside Heights', 'Morrisania', 'Two Bridges',
       'Concourse', 'Downtown Brooklyn', 'Queens Village', 'Fieldston',
       'Allerton', 'Grymes Hill', 'Carroll Gardens', 'Kingsbridge',
       'Belle Harbor', 'NoHo', 'Maspeth', 'Borough Park', 'Midwood',
       'Fresh Meadows', 'Battery Park City', 'Pelham Bay', 'Van Nest',
       'Long Island City', 'Williamsbridge', 'Nolita', 'Kew Gardens',
       'Corona', 'Middle Village', 'Jackson Heights', 'Gravesend',
       'New Dorp Beach', 'Brighton Beach', 'Belmont', 'Eltingville',
       'South Ozone Park', 'Stuyvesant Town', 'Far Rockaway', 'Longwood',
       'Glendale', 'Dongan Hills', 'Hollis', 'Columbia St',
       'Tompkinsville', 'Springfield Gardens', 'Concourse Village',
       'Throgs Neck', 'Cobble Hill', 'South Beach', 'North Riverdale',
       'Rosedale', 'Mount Hope', 'Edenwald', 'Parkchester', 'Mill Basin',
       'Brownsville', 'Fort Hamilton', 'Howard Beach',
       'Claremont Village', 'Pelham Gardens', 'Westchester Square',
       'Kew Gardens Hills', 'Arrochar', 'Edgemere', 'Shore Acres',
       'Dyker Heights', 'Mount Eden', 'Randall Manor', 'Jamaica Hills',
       'Norwood', 'Tottenville', 'Cambria Heights', 'East Morrisania',
       'Soundview', 'Morris Park', 'Bronxdale', 'Bellerose', 'Navy Yard',
       'Unionport', 'DUMBO', 'Bayswater', 'Tremont', 'Highbridge',
       'Graniteville', 'Baychester', 'Morris Heights', 'Coney Island',
       'Briarwood', 'West Farms', "Prince's Bay", 'University Heights',
       'Clifton', 'Bay Terrace', 'City Island', 'West Brighton',
       'Douglaston', 'Schuylerville', 'Port Richmond', 'Oakwood',
       'Westerleigh', 'Little Neck', 'Holliswood', 'Bergen Beach',
       'Castle Hill', 'Olinville', 'Rosebank', 'Melrose', 'Whitestone',
       'Grant City', 'Riverdale', 'Neponsit', 'Bath Beach',
       'Mariners Harbor', 'Hunts Point', 'Great Kills', 'Midland Beach',
       'Eastchester', 'Jamaica Estates', 'New Springville'], dtype=object)

In [34]:
airbnb.drop(airbnb[airbnb['rating'] > 5.0].index, inplace=True)
airbnb[airbnb['rating']>5.0].info

<bound method DataFrame.info of Empty DataFrame
Columns: [listing_id, name, host_id, host_name, coordinates, room_type, price, number_of_reviews, last_review, reviews_per_month, availability_365, rating, number_of_stays, 5_stars, listing_added, latitude, longitude, borough, neighbourhood]
Index: []>

In [35]:
airbnb[airbnb['rating'].isna()].describe()

,listing_id,host_id,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude
count,2.075000e+03,2.075000e+03,2028.000000,2075.0,0,0.0,2075.000000,0.0,0.0,0.0,2075,2075.000000,2075.000000
mean,2.274238e+07,8.022455e+07,191.553748,0.0,NaT,NaN,104.531566,NaN,NaN,NaN,2018-06-08 17:01:31.951807232,40.732074,-73.956771
min,6.358800e+04,1.475100e+04,0.000000,0.0,NaT,NaN,0.000000,NaN,NaN,NaN,2018-02-03 00:00:00,40.527000,-74.209410
25%,1.232923e+07,1.224305e+07,70.000000,0.0,NaT,NaN,0.000000,NaN,NaN,NaN,2018-04-05 00:00:00,40.697845,-73.985185
50%,2.345182e+07,4.040116e+07,120.000000,0.0,NaT,NaN,7.000000,NaN,NaN,NaN,2018-06-05 00:00:00,40.727790,-73.960940
75%,3.400364e+07,1.333498e+08,205.250000,0.0,NaT,NaN,211.000000,NaN,NaN,NaN,2018-08-13 00:00:00,40.763480,-73.939540
max,3.648724e+07,2.741034e+08,5250.000000,0.0,NaT,NaN,365.000000,NaN,NaN,NaN,2018-10-17 00:00:00,40.911690,-73.727310
std,1.123730e+07,8.663163e+07,316.186639,0.0,NaN,NaN,138.266525,NaN,NaN,NaN,NaN,0.051168,0.041065

In [36]:
airbnb[~airbnb['rating'].isna()].describe

<bound method NDFrame.describe of        listing_id                                               name  \
0        13740704  Cozy,budget friendly, cable inc, private entra...
1        22005115              Two floor apartment near Central Park
3         6425850                          Spacious, charming studio
4        22986519              Bedroom on the lively Lower East Side
5          271954                     Beautiful brownstone apartment
...           ...                                                ...
10014    22307861                        Lovely 1BR Harlem apartment
10015      953275                Apartment For Your Holidays in NYC!
10016     3452835          Artsy, Garden Getaway in Central Brooklyn
10017    23540194     Immaculate townhouse in Clinton Hill, Brooklyn
10018    32876011     Private room in a perfect location in the city

         host_id host_name                   coordinates     room_type  price  \
0       20583125    Michel           40.63222, -73.93398  Private Room   45.0
1       82746113   Cecilia           40.78761, -73.96862  Entire place  135.0
3       32715865    Yelena           40.79169, -73.97498  Entire place   86.0
4      154262349    Brooke           40.71884, -73.98354  Private Room  160.0
5        1423798        Aj           40.73388, -73.99452  Entire place  150.0
...          ...       ...                           ...           ...    ...
10014   16004068    Rachel           40.80379, -73.95257  Entire place  105.0
10015    4460034     Alain            40.79531, -73.9333  Entire place  125.0
10016     666862       Amy  40.68266, -73.96743000000002  Entire place  100.0
10017   67176930    Sophie           40.68832, -73.96366  Entire place  450.0
10018   59583716      Shai           40.76174, -73.96625  Private Room   90.0

       number_of_reviews last_review  reviews_per_month  availability_365  \
0                     10  2018-12-12               0.70                85
1                      1  2019-06-30               1.00               145
3                      5  2017-09-23               0.13                 0
4                     23  2019-06-12               2.29               102
5                    203  2019-06-20               2.22               300
...                  ...         ...                ...               ...
10014                  4  2018-05-28               0.21                 0
10015                 50  2018-05-06               0.66               188
10016                 45  2016-11-27               0.98                 0
10017                  2  2019-05-31               0.17                99
10018                  1  2019-03-12               0.25                 8

         rating  number_of_stays   5_stars listing_added  latitude  longitude  \
0      4.100954             12.0  0.609432    2018-06-08  40.63222  -73.93398
1      3.367600              1.2  0.746135    2018-12-25  40.78761  -73.96862
3      4.763203              6.0  0.769947    2017-03-20  40.79169  -73.97498
4      3.822591             27.6  0.649383    2020-10-23  40.71884  -73.98354
5      4.478396            243.6  0.743500    2018-12-15  40.73388  -73.99452
...         ...              ...       ...           ...       ...        ...
10014  4.757555              4.8  0.639223    2017-11-22  40.80379  -73.95257
10015  4.344704             60.0  0.648778    2017-10-31  40.79531  -73.93330
10016  3.966214             54.0  0.631713    2016-05-24  40.68266  -73.96743
10017  4.078581              2.4  0.703360    2018-11-25  40.68832  -73.96366
10018  4.069096              1.2  0.720249    2018-09-06  40.76174  -73.96625

         borough      neighbourhood
0       Brooklyn          Flatlands
1      Manhattan    Upper West Side
3      Manhattan    Upper West Side
4      Manhattan    Lower East Side
5      Manhattan  Greenwich Village
...          ...                ...
10014  Manhattan             Harlem
10015  Manhattan        East Harlem
10016   Brooklyn       Clinton Hill
10017   Brooklyn       Clinton Hill
10018  Manhattan    Upper East Side

[7941 rows x 19 columns]>

In [38]:
airbnb =  airbnb.fillna({
    'reviews_per_month':0,
    'number_of_stays':0,
    '5_stars':0
})

In [39]:
is_rated = np.where(airbnb['rating'].isna()==True,0,1)
airbnb['is_rated']=is_rated
airbnb

,listing_id,name,host_id,host_name,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude,borough,neighbourhood,is_rated
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"40.63222, -73.93398",Private Room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398,Brooklyn,Flatlands,1
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"40.78761, -73.96862",Entire place,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862,Manhattan,Upper West Side,1
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"40.7007, -73.99517",Entire place,150.0,0,NaT,0.00,65,NaN,0.0,0.000000,2018-08-15,40.70070,-73.99517,Brooklyn,Brooklyn Heights,0
3,6425850,"Spacious, charming studio",32715865,Yelena,"40.79169, -73.97498",Entire place,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498,Manhattan,Upper West Side,1
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"40.71884, -73.98354",Private Room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354,Manhattan,Lower East Side,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"40.80379, -73.95257",Entire place,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257,Manhattan,Harlem,1
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"40.79531, -73.9333",Entire place,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.93330,Manhattan,East Harlem,1
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"40.68266, -73.96743000000002",Entire place,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743,Brooklyn,Clinton Hill,1
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"40.68832, -73.96366",Entire place,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366,Brooklyn,Clinton Hill,1
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"40.76174, -73.96625",Private Room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625,Manhattan,Upper East Side,1

In [40]:
airbnb[airbnb['price'].isna()].count()

listing_id           238
name                 238
host_id              238
host_name            238
coordinates          238
room_type            238
price                  0
number_of_reviews    238
last_review          191
reviews_per_month    238
availability_365     238
rating               191
number_of_stays      238
5_stars              238
listing_added        238
latitude             238
longitude            238
borough              238
neighbourhood        238
is_rated             238
dtype: int64

In [42]:
airbnb.isnull().sum()

listing_id              0
name                    5
host_id                 0
host_name               2
coordinates             0
room_type               0
price                 238
number_of_reviews       0
last_review          2075
reviews_per_month       0
availability_365        0
rating               2075
number_of_stays         0
5_stars                 0
listing_added           0
latitude                0
longitude               0
borough                 0
neighbourhood           0
is_rated                0
dtype: int64

In [43]:
airbnb.loc[(airbnb['price'].isna())&(airbnb['room_type']=='Entire place'),'price']=163.0
airbnb.loc[(airbnb['price'].isna())&(airbnb['room_type']=='Private Room'),'price']=70.0
airbnb.loc[(airbnb['price'].isna())&(airbnb['room_type']=='Shared Room'),'price']=50.0

In [44]:
airbnb[airbnb['price'].isna()]

,listing_id,name,host_id,host_name,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude,borough,neighbourhood,is_rated
508,13974200,"Sunny, Pre-War Brooklyn Share",77317167,Stacey Rae,"40.65126, -73.96388",Shared room,NaN,5,2017-10-01,0.15,0,4.752003,6.0,0.658378,2017-03-28,40.65126,-73.96388,Brooklyn,Flatbush,1
1043,33431709,Shared apartment by the Central Park,251852817,Owen,"40.80073, -73.94328",Shared room,NaN,17,2019-06-30,5.10,72,4.683608,20.4,0.917779,2018-12-25,40.80073,-73.94328,Manhattan,East Harlem,1
2086,36118872,A Cozy Bed Dream in Manhattan,178720348,Mingmei,"40.81851, -73.9567",Shared room,NaN,0,NaT,0.00,34,NaN,0.0,0.000000,2018-03-28,40.81851,-73.95670,Manhattan,Harlem,0
3353,21568943,Shareroom in Midtown Manhattan 1or2 beds Avail...,156246842,Sandra,"40.7614, -73.98682",Shared room,NaN,9,2018-08-01,0.45,0,4.382015,10.8,0.634106,2018-01-26,40.76140,-73.98682,Manhattan,Hell's Kitchen,1
3909,30950573,Brooklyn 3 persons shared room close to subway,17706542,Sergey,"40.6919, -73.90626",Shared room,NaN,0,NaT,0.00,342,NaN,0.0,0.000000,2018-09-25,40.69190,-73.90626,Brooklyn,Bushwick,0
8212,7711899,FEMALE ONLY 'Heaven'PrivateBed/SharedSpace w/Wifi,40509550,Denise,"40.84805, -73.94209000000002",Shared room,NaN,14,2018-11-01,0.30,363,4.226222,16.8,0.680988,2018-04-28,40.84805,-73.94209,Manhattan,Washington Heights,1
9793,6155877,Solo traveler oasis,18248926,Yana,"40.82434, -73.94816",Shared room,NaN,84,2019-06-15,2.26,347,4.086250,100.8,0.601364,2018-12-10,40.82434,-73.94816,Manhattan,Harlem,1

In [45]:
airbnb.isna().sum()

listing_id              0
name                    5
host_id                 0
host_name               2
coordinates             0
room_type               0
price                   7
number_of_reviews       0
last_review          2075
reviews_per_month       0
availability_365        0
rating               2075
number_of_stays         0
5_stars                 0
listing_added           0
latitude                0
longitude               0
borough                 0
neighbourhood           0
is_rated                0
dtype: int64

In [46]:
inconsistent_dates = airbnb[airbnb['listing_added'].dt.date>airbnb['last_review'].dt.date]
inconsistent_dates

,listing_id,name,host_id,host_name,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude,borough,neighbourhood,is_rated
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"40.71884, -73.98354",Private Room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354,Manhattan,Lower East Side,1
50,20783900,Marvelous Manhattan Marble Hill Private Suites,148960265,Randy,"40.87618, -73.91266",Private Room,93.0,7,2018-10-06,0.32,0,4.868036,8.4,0.609263,2020-02-17,40.87618,-73.91266,Manhattan,Marble Hill,1
60,1908852,Oversized Studio By Columbus Circle,684629,Alana,"40.7706, -73.98919000000002",Entire place,189.0,7,2016-05-06,0.13,0,4.841204,8.4,0.725995,2017-09-17,40.77060,-73.98919,Manhattan,Upper West Side,1
124,28659894,Private bedroom in prime Bushwick! Near Trains!!!,216235179,Nina,"40.69988, -73.92071999999997",Private Room,55.0,4,2019-04-12,0.58,358,4.916252,4.8,0.703117,2020-08-23,40.69988,-73.92072,Brooklyn,Bushwick,1
511,33619855,Modern & Spacious in trendy Crown Heights,253354074,Yehudis,"40.66387, -73.9384",Entire place,150.0,6,2019-05-27,2.50,148,3.462432,7.2,0.610929,2020-10-07,40.66387,-73.93840,Brooklyn,Crown Heights,1
521,25317793,Awesome Cozy Room in The Heart of Sunnyside!,136406167,Kara,"40.7409, -73.92696",Private Room,65.0,22,2019-06-11,1.63,131,4.442485,26.4,0.722388,2020-10-22,40.74090,-73.92696,Queens,Sunnyside,1

In [47]:
airbnb.drop(inconsistent_dates.index,inplace=True)

In [48]:
airbnb = airbnb.duplicated(subset='listing_id',keep = False)

In [49]:
duplicates = airbnb.duplicated(subset='listing_id',keep = False)
print(duplicates)

TypeError: Series.duplicated() got an unexpected keyword argument 'subset'