In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df  = pd.read_csv('titanic (1).csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [4]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

In [5]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Age'].isnull().sum()

C:\Users\Rudra Pratap Singh\AppData\Local\Temp\ipykernel_10856\1401360216.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

np.int64(0)

In [6]:
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,28.0,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [8]:
df['Cabin'] = df['Cabin'].fillna('Unknown')

In [9]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [10]:
X = pd.get_dummies(X, drop_first=True)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,
                    test_size=0.2,random_state=42,stratify=y)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression")
print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1 Score :", f1_score(y_test, y_pred_lr))

Logistic Regression
Accuracy : 0.7039106145251397
Precision: 0.7
Recall   : 0.4057971014492754
F1 Score : 0.5137614678899083

In [15]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree")
print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))

Decision Tree
Accuracy : 0.776536312849162
Precision: 0.7164179104477612
Recall   : 0.6956521739130435
F1 Score : 0.7058823529411765

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest")
print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))

Random Forest
Accuracy : 0.7932960893854749
Precision: 0.7580645161290323
Recall   : 0.6811594202898551
F1 Score : 0.7175572519083969

In [17]:
from sklearn.model_selection import KFold, cross_validate

kf = KFold(n_splits=5, shuffle=True, random_state=42)

dt = DecisionTreeClassifier(random_state=42)

scoring = ['accuracy', 'precision', 'recall', 'f1']

dt_scores = cross_validate(dt, X_scaled, y, cv=kf, scoring=scoring)

print("Decision Tree with K-Fold")
for metric in scoring:
    print(metric, dt_scores['test_' + metric].mean())

Decision Tree with K-Fold
accuracy 0.8047266336074321
precision 0.7934864255356059
recall 0.6625058416103192
f1 0.7192780354400413

In [18]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf_scores = cross_validate(rf, X_scaled, y, cv=skf, scoring=scoring)

print("Random Forest with Stratified K-Fold")
for metric in scoring:
    print(metric, rf_scores['test_' + metric].mean())

Random Forest with Stratified K-Fold
accuracy 0.8327725817588348
precision 0.8417126062888777
recall 0.6959079283887468
f1 0.7614584236790425

In [19]:
comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Decision Tree',
        'Random Forest',
        'Decision Tree (KFold)',
        'Random Forest (Stratified KFold)'
    ],
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf),
        dt_scores['test_accuracy'].mean(),
        rf_scores['test_accuracy'].mean()
    ],
    'Precision': [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_rf),
        dt_scores['test_precision'].mean(),
        rf_scores['test_precision'].mean()
    ],
    'Recall': [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_rf),
        dt_scores['test_recall'].mean(),
        rf_scores['test_recall'].mean()
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_rf),
        dt_scores['test_f1'].mean(),
        rf_scores['test_f1'].mean()
    ]
})

print(comparison)

                              Model  Accuracy  Precision    Recall  F1 Score
0               Logistic Regression  0.703911   0.700000  0.405797  0.513761
1                     Decision Tree  0.776536   0.716418  0.695652  0.705882
2                     Random Forest  0.793296   0.758065  0.681159  0.717557
3             Decision Tree (KFold)  0.804727   0.793486  0.662506  0.719278
4  Random Forest (Stratified KFold)  0.832773   0.841713  0.695908  0.761458

In [20]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [23]:
print(X_train)

[[ 0.96030711  0.82737724 -0.1046374  ...  0.54492498 -0.30756234
   0.61930636]
 [ 0.13996379 -0.36936484 -0.1046374  ...  0.54492498 -0.30756234
   0.61930636]
 [ 0.31880641 -1.56610693 -0.1046374  ... -1.835115   -0.30756234
   0.61930636]
 ...
 [ 1.13137397  0.82737724  1.43235947 ...  0.54492498 -0.30756234
   0.61930636]
 [ 0.06609401 -1.56610693  1.35550962 ... -1.835115   -0.30756234
   0.61930636]
 [ 0.24104875 -1.56610693 -0.1046374  ...  0.54492498 -0.30756234
   0.61930636]]