In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snb

In [2]:
data = pd.read_csv('spam.csv',encoding='latin')
data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
data['spam']=data['Category'].apply(lambda x:1 if x=='spam' else 0)
data

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.Message, data.spam,test_size=0.25,random_state=42)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
b = CountVectorizer()

In [6]:
x_train_count =b.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7489))

In [7]:
from sklearn.naive_bayes import MultinomialNB
mod1 = MultinomialNB()
mod1.fit(x_train_count,y_train)

MultinomialNB()

In [8]:
emails=["we have a annual meeting at 2.00pm",
       "you have 90% sales flat off on www.perfumes.com","offer!!!"]

In [9]:
e_emails = b.transform(emails)

In [10]:
e_emails

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (3, 7489)>

In [11]:
x_test_count = b.transform(x_test)

In [12]:
mod1.score(x_test_count,y_test)

0.9885139985642498

In [13]:
mod1.predict(e_emails)

array([0, 1, 1])

In [14]:
pred = mod1.predict(x_test_count)

In [16]:
from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[1203    4]
 [  12  174]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1207
           1       0.98      0.94      0.96       186

    accuracy                           0.99      1393
   macro avg       0.98      0.97      0.97      1393
weighted avg       0.99      0.99      0.99      1393