In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('pulsar_stars.csv')
df

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
17893,136.429688,59.847421,-0.187846,-0.738123,1.296823,12.166062,15.450260,285.931022,0
17894,122.554688,49.485605,0.127978,0.323061,16.409699,44.626893,2.945244,8.297092,0
17895,119.335938,59.935939,0.159363,-0.743025,21.430602,58.872000,2.499517,4.595173,0
17896,114.507812,53.902400,0.201161,-0.024789,1.946488,13.381731,10.007967,134.238910,0
17897,57.062500,85.797340,1.406391,0.089520,188.306020,64.712562,-1.597527,1.429475,0

In [2]:
df.columns = df.columns.str.strip()

In [3]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [4]:
df.columns=['IP Mean','IP Sd','IP Kurtosis','IP Skewness','DM-SNR Mean','DM-SNR Sd','DM-SNR Kurtosis',
           'DM-SNR Skewness','target_class']

In [5]:
df.columns

Index(['IP Mean', 'IP Sd', 'IP Kurtosis', 'IP Skewness', 'DM-SNR Mean',
       'DM-SNR Sd', 'DM-SNR Kurtosis', 'DM-SNR Skewness', 'target_class'],
      dtype='object')

In [6]:
df['target_class'].value_counts()

target_class
0    16259
1     1639
Name: count, dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IP Mean          17898 non-null  float64
 1   IP Sd            17898 non-null  float64
 2   IP Kurtosis      17898 non-null  float64
 3   IP Skewness      17898 non-null  float64
 4   DM-SNR Mean      17898 non-null  float64
 5   DM-SNR Sd        17898 non-null  float64
 6   DM-SNR Kurtosis  17898 non-null  float64
 7   DM-SNR Skewness  17898 non-null  float64
 8   target_class     17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [8]:
X=df.drop(['target_class'],axis=1)
y=df['target_class']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
X_train.shape,X_test.shape

((14318, 8), (3580, 8))

In [11]:
cols=X_train.columns

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train = pd.DataFrame(X_train,columns=[cols])

In [14]:
X_test = pd.DataFrame(X_test,columns=[cols])

In [15]:
X_train.describe()

,IP Mean,IP Sd,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR Sd,DM-SNR Kurtosis,DM-SNR Skewness
count,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04,1.431800e+04
mean,1.923001e-16,-6.550610e-16,5.855849e-17,3.970067e-17,-8.833399e-17,1.989996e-16,-1.439149e-17,-2.828673e-17
std,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00,1.000035e+00
min,-4.035499e+00,-3.181033e+00,-2.185946e+00,-5.744051e-01,-4.239001e-01,-9.733707e-01,-2.455649e+00,-1.003411e+00
25%,-3.896291e-01,-6.069473e-01,-4.256221e-01,-3.188054e-01,-3.664918e-01,-6.125457e-01,-5.641035e-01,-6.627590e-01
50%,1.587461e-01,5.846646e-02,-2.453172e-01,-2.578142e-01,-3.372294e-01,-4.067482e-01,3.170446e-02,-2.059136e-01
75%,6.267059e-01,6.501017e-01,-1.001238e-02,-1.419621e-01,-2.463724e-01,1.078934e-01,5.362759e-01,3.256217e-01
max,3.151882e+00,7.621116e+00,7.008906e+00,1.054430e+01,7.025568e+00,4.292181e+00,5.818557e+00,1.024613e+01

In [16]:
# import SVC Classifier
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score
svc = SVC()

svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
accuracy_score(y_test, y_pred)
print('Model accuracy scre with default hyperparameters: {0:0.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy scre with default hyperparameters: 0.9827

In [17]:
svc = SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)

print('Model accuracy score with rbf kernel and c=100.0:{0:0.4f}'.
    format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and c=100.0:0.9832

In [19]:
linear_svc = SVC(kernel='linear',C=1.0)
linear_svc.fit(X_train,y_train)
y_pred_test = linear_svc.predict(X_test)

print('Model accuracy score with linear kernel and c=1.0:{0:0.4f}'.
    format(accuracy_score(y_test,y_pred_test)))

Model accuracy score with linear kernel and c=1.0:0.9830

In [21]:
poly_svc =SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred = poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and c=1.0:{0:0.4f}'.
    format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and c=1.0:0.9807