In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('50_Startups.csv')
df.head()
X = df.drop(columns=['Profit'])
y = df.iloc[:,-1:]
X = pd.get_dummies(X,columns=['State'],drop_first=True,dtype=int)

from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Scale X
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame (optional but recommended)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print(X_scaled.head())

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   2.016411        0.560753         2.153943      -0.685994        1.393261
1   1.955860        1.082807         1.923600      -0.685994       -0.717741
2   1.754364       -0.728257         1.626528       1.457738       -0.717741
3   1.554784       -0.096365         1.422210      -0.685994        1.393261
4   1.504937       -1.079919         1.281528       1.457738       -0.717741

In [43]:
X

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [44]:
y

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [33]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred = regressor.predict(x_test)

In [35]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print("mse",mean_squared_error(y_test,y_pred))
print("rmse",rmse)

mse 82010363.04430112
rmse 9055.957323458471

In [36]:
print(regressor.intercept_)
print(regressor.coef_)

[54028.03959365]
[[ 8.05630064e-01 -6.87878823e-02  2.98554429e-02  9.38793006e+02
   6.98775997e+00]]

In [37]:
import statsmodels.api as sm
x_train=sm.add_constant(x_train)
x_test=sm.add_constant(x_test)
model=sm.OLS(y_train,x_train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.954
Model:                            OLS   Adj. R-squared:                  0.947
Method:                 Least Squares   F-statistic:                     140.1
Date:                Thu, 06 Aug 2026   Prob (F-statistic):           1.13e-21
Time:                        10:58:57   Log-Likelihood:                -420.63
No. Observations:                  40   AIC:                             853.3
Df Residuals:                      34   BIC:                             863.4
Df Model:                           5
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.403e+04   8457.293      6.388      0.000    3.68e+04    7.12e+04
R&D Spend           0.8056      0.052     15.383      0.000       0.699       0.912
Administration     -0.0688      0.061     -1.133      0.265      -0.192       0.055
Marketing Spend     0.0299      0.022      1.346      0.187      -0.015       0.075
State_Florida     938.7930   3893.511      0.241      0.811   -6973.773    8851.359
State_New York      6.9878   3882.765      0.002      0.999   -7883.740    7897.715
==============================================================================
Omnibus:                       15.391   Durbin-Watson:                   1.751
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               20.231
Skew:                          -1.142   Prob(JB):                     4.05e-05
Kurtosis:                       5.631   Cond. No.                     1.64e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.64e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [38]:
x_train = x_train.iloc[:,:-1]
model=sm.OLS(y_train,x_train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.954
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     180.2
Date:                Thu, 06 Aug 2026   Prob (F-statistic):           7.85e-23
Time:                        10:59:06   Log-Likelihood:                -420.63
No. Observations:                  40   AIC:                             851.3
Df Residuals:                      35   BIC:                             859.7
Df Model:                           4
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.403e+04   8274.043      6.530      0.000    3.72e+04    7.08e+04
R&D Spend           0.8056      0.052     15.614      0.000       0.701       0.910
Administration     -0.0688      0.060     -1.150      0.258      -0.190       0.053
Marketing Spend     0.0299      0.022      1.374      0.178      -0.014       0.074
State_Florida     935.0793   3254.211      0.287      0.776   -5671.320    7541.479
==============================================================================
Omnibus:                       15.396   Durbin-Watson:                   1.751
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               20.244
Skew:                          -1.142   Prob(JB):                     4.02e-05
Kurtosis:                       5.633   Cond. No.                     1.63e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.63e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [39]:
x_train = x_train.iloc[:,:-1]
model=sm.OLS(y_train,x_train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.954
Model:                            OLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     246.6
Date:                Thu, 06 Aug 2026   Prob (F-statistic):           4.76e-24
Time:                        10:59:29   Log-Likelihood:                -420.68
No. Observations:                  40   AIC:                             849.4
Df Residuals:                      36   BIC:                             856.1
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.407e+04   8166.660      6.621      0.000    3.75e+04    7.06e+04
R&D Spend           0.8038      0.051     15.906      0.000       0.701       0.906
Administration     -0.0679      0.059     -1.152      0.257      -0.188       0.052
Marketing Spend     0.0312      0.021      1.493      0.144      -0.011       0.074
==============================================================================
Omnibus:                       15.613   Durbin-Watson:                   1.759
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               21.146
Skew:                          -1.137   Prob(JB):                     2.56e-05
Kurtosis:                       5.742   Cond. No.                     1.63e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.63e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [40]:
x_train = x_train.iloc[:,[0,1,3]]
model=sm.OLS(y_train,x_train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.952
Model:                            OLS   Adj. R-squared:                  0.949
Method:                 Least Squares   F-statistic:                     366.0
Date:                Thu, 06 Aug 2026   Prob (F-statistic):           4.19e-25
Time:                        10:59:58   Log-Likelihood:                -421.40
No. Observations:                  40   AIC:                             848.8
Df Residuals:                      37   BIC:                             853.9
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            4.554e+04   3457.277     13.173      0.000    3.85e+04    5.25e+04
R&D Spend           0.7834      0.048     16.480      0.000       0.687       0.880
Marketing Spend     0.0392      0.020      1.980      0.055      -0.001       0.079
==============================================================================
Omnibus:                       13.869   Durbin-Watson:                   1.753
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.958
Skew:                          -1.067   Prob(JB):                     0.000208
Kurtosis:                       5.371   Cond. No.                     6.36e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.36e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [48]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
x_train=sm.add_constant(x_train)
x_test=sm.add_constant(x_test)
regressor=LinearRegression()
sfs = SequentialFeatureSelector(regressor,n_features_to_select=2,direction='forward')
sfs.fit(x_train,y_train)
print(sfs.get_support())
print(x_train.columns[sfs.get_support()])

[False  True  True False False False]
Index(['R&D Spend', 'Administration'], dtype='object')

In [64]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
x_train=sm.add_constant(x_train)
x_test=sm.add_constant(x_test)
regressor=LinearRegression()
sfs = SequentialFeatureSelector(regressor,n_features_to_select='auto',tol=0.00179,direction='forward')
sfs.fit(x_train,y_train)
print(sfs.get_support())
print(x_train.columns[sfs.get_support()])

[False  True  True False False False]
Index(['R&D Spend', 'Administration'], dtype='object')

In [ ]:
#recursive feature elimination

In [69]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
rfe = RFE(estimator=regressor,n_features_to_select=2)
rfe.fit(x_train,y_train)

selected_features=x_train.columns[rfe.support_]
print(selected_features)

Index(['R&D Spend', 'Marketing Spend'], dtype='object')

In [74]:
from sklearn.linear_model import Lasso,Ridge
ls = Lasso(alpha=100)
ls.fit(x_train,y_train)
rdg = Ridge()
rdg.fit(x_train,y_train)
print(rdg.coef_)
print(ls.coef_)

[34753.1345367  -1423.16670463  5076.01541871   341.06791068
    68.75714761]
[36503.8847558  -1786.80645111  3619.50205216   349.24437337
    -0.        ]

In [75]:
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(alphas=[0.1,1,10,100,1000],cv = 5,max_iter=100000)
lasso_cv.fit(x_train,y_train)
print(lasso_cv.alpha_)

1000.0

C:\Users\Rudra Pratap Singh\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1714: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [77]:
from sklearn.linear_model import RidgeCV
rdg_cv = RidgeCV(alphas=[0.1,1,10,100,1000],cv = 5)
rdg_cv.fit(x_train,y_train)
print(rdg_cv.alpha_)

0.1